name: Update Stars Badge

on:
  watch:
    types: [started]
  push:
    branches: [main]
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Stars Badge
        run: |
          STARS=$(curl -s "https://api.github.com/repos/${{ github.repository }}" | jq '.stargazers_count')
          sed -i "s/img.shields.io\/github\/stars\/.*style=social/img.shields.io\/github\/stars\/${{ github.repository }}\?style=social\&label=Stars\&count=${STARS}/" README.md

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: Update star count badge'
          file_pattern: 'README.md'
